name: Markdown Lint Check

on:
  pull_request:

permissions:
  contents: read

jobs:
  markdownlint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install markdownlint-cli2
        run: npm install -g markdownlint-cli2

      - name: "Run Markdown Lint Check"
        run: make markdown-lint